version: '3'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3333:3333
  #   environment:
  #     - DATABASE_URL=mongodb://monty:pass@mongo_supertest:27017/pos-tech-diner-db?authSource=admin&directConnection=true
  #   networks:
  #     - pos-tech-pedido-teste
  
  localstack:
    image: localstack/localstack:3.1.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "./local-data/localstack_data:/var/lib/localstack"
    networks:
      - pos-tech-pedido-teste

networks:
  pos-tech-pedido-teste:
    external: true

volumes:
  local-data: